name: Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
        image: python:3.9
        options: --user root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt-get update -qy
          apt-get install -y build-essential gcc g++ python python3 sudo
          git clone https://github.com/nsnam/ns-3-allinone.git
          cd ns-3-allinone
          ./download.py -n ns-3.33
          cd ns-3.33
          ./build.py -- --enable-examples --enable-tests
        working-directory: ${{ github.workspace }}

      - name: Build C++ Code
        uses: parasoft/run-cpptest-action@2.0.1
        with:
          installDir: '/src/antenna/'     
      - name: Run Tests and Generate Coverage
        continue-on-error: true
        run: |
          # Set PYTHONPATH and navigate to the tests directory
          export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages
          cd $GITHUB_WORKSPACE
          
          # Run tests and generate coverage report
          python3 -m coverage run -m pytest
          python3 -m coverage xml --omit="/opt/*,/root/*,/tmp/*,/usr/*,/var/*,**/__init__.py"
      - name: Build Python Code
        run: |
          cd ns-3_c-v2x
          # Replace with your Python build commands
          python setup.py build
        working-directory: ${{ github.workspace }}

      - name: Test Python Code
        run: |
          cd ns-3_c-v2x
          # Replace with your Python test commands
          python setup.py test
        working-directory: ${{ github.workspace }}
